### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by nithyasharabheshwara** [mdPlusPlus/yt-load#1]
I believe you are trying to make youtube-dl run on java.
Nice project.
Is it working? What is the current status?

**Comment by mdPlusPlus** [comment]
I'm looking into replacing my [yt-lib](https://github.com/mdPlusPlus/yt-lib) with [youtube-dl](https://github.com/rg3/youtube-dl/). Since the JVM is able to run Python code with [Jython](http://www.jython.org/), this would provide a cross-platform java frontend for youtube-dl, without the need for python.

The current code base hower does not use youtube-dl yet, and therefore can't handle encrypted or age-restricted content. Everything else should work fine.

As you can see, the latest commit to my project has been a while ago and currently I'm not working on it, so I can't make any promises on when or whether I'm going to implement it.
